server:
  port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/Note_db?createDatabaseIfNotExist=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Derek





    jpa:
         hibernate:
            ddl-auto: update
         database-platform: org.hibernate.dialect.MySQL8Dialect


